#!/bin/bash
#
# build-runner-template.sh — Build a Proxmox LXC template with the
# GitHub Actions runner + Docker + common build/test system libraries.
#
# Run as root on a Proxmox node. See template-builder/README.md.
#
# shellcheck disable=SC2034
# Reason: configuration variables below are referenced by step functions
# wired in across multiple tasks; SC2034 is a known false-positive here.

set -euo pipefail

# === Configuration ===========================================================

TEMPLATE_VMID="${TEMPLATE_VMID:-9000}"
STORAGE_POOL="${STORAGE_POOL:-local-lvm}"
BRIDGE="${BRIDGE:-vmbr0}"
UBUNTU_VERSION="${UBUNTU_VERSION:-24.04}"

# Pinned GitHub Actions runner. Bump both together via PR.
# Latest releases: https://github.com/actions/runner/releases
RUNNER_VERSION="0.0.0"   # set in Task 10
RUNNER_SHA256="0000000000000000000000000000000000000000000000000000000000000000"  # set in Task 10

# Self-install paths
INSTALL_PATH="/usr/local/sbin/build-runner-template.sh"
CRON_PATH="/etc/cron.d/build-runner-template"
CRON_SCHEDULE="0 3 1 */3 *"   # 03:00 on day 1 of Jan/Apr/Jul/Oct

# Resolved by ensure_ubuntu_template().
UBUNTU_TEMPLATE_FILENAME=""

# === Helpers =================================================================

log() {
    printf '[%s] %s\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "$*"
}

on_err() {
    local line=$1
    log "FAILED at line ${line}"
}
trap 'on_err $LINENO' ERR

# Run a multi-line bash snippet inside the template container.
# Usage:
#   in_container "$(cat <<'EOF'
#     set -euo pipefail
#     apt-get update
#   EOF
#   )"
in_container() {
    pct exec "$TEMPLATE_VMID" -- bash -c "$1"
}

# === Steps ===================================================================

preflight() {
    log "pre-flight checks"

    if [[ $EUID -ne 0 ]]; then
        log "must run as root"
        exit 1
    fi

    local cmd
    for cmd in pct pveam pvesm; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            log "required command not found: ${cmd}"
            exit 1
        fi
    done

    if ! pvesm status | awk 'NR>1 {print $1}' | grep -qx "$STORAGE_POOL"; then
        log "storage pool not found: ${STORAGE_POOL}"
        exit 1
    fi

    if [[ ! -d "/sys/class/net/${BRIDGE}" ]]; then
        log "bridge not found: ${BRIDGE}"
        exit 1
    fi
}

self_install() {
    local src
    src="$(readlink -f "$0")"

    if [[ "$src" != "$INSTALL_PATH" ]]; then
        log "installing self to ${INSTALL_PATH}"
        install -m 0755 "$src" "$INSTALL_PATH"
    fi

    log "writing cron entry to ${CRON_PATH}"
    cat > "$CRON_PATH" <<EOF
# Rebuild the GitHub Actions runner LXC template.
# Generated by build-runner-template.sh — overwritten on every run.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
${CRON_SCHEDULE} root ${INSTALL_PATH} >> /var/log/build-runner-template.log 2>&1
EOF
    chmod 0644 "$CRON_PATH"
}

ensure_ubuntu_template() {
    log "ensuring ubuntu ${UBUNTU_VERSION} base template is present"

    pveam update >/dev/null

    local existing
    existing="$(pveam list local \
        | awk 'NR>1 {print $1}' \
        | sed 's|^local:vztmpl/||' \
        | grep -E "^ubuntu-${UBUNTU_VERSION}-standard_.*_amd64\.tar\.zst$" \
        | sort \
        | tail -n1 || true)"

    if [[ -n "$existing" ]]; then
        UBUNTU_TEMPLATE_FILENAME="$existing"
        log "found existing template: ${UBUNTU_TEMPLATE_FILENAME}"
        return
    fi

    local available
    available="$(pveam available --section system \
        | awk '{print $2}' \
        | grep -E "^ubuntu-${UBUNTU_VERSION}-standard_.*_amd64\.tar\.zst$" \
        | sort \
        | tail -n1 || true)"

    if [[ -z "$available" ]]; then
        log "no ubuntu ${UBUNTU_VERSION} template available from pveam"
        exit 1
    fi

    log "downloading ${available}"
    pveam download local "$available"
    UBUNTU_TEMPLATE_FILENAME="$available"
}

reset_vmid() {
    if pct status "$TEMPLATE_VMID" >/dev/null 2>&1; then
        log "destroying existing VMID ${TEMPLATE_VMID}"
        pct stop "$TEMPLATE_VMID" --skiplock >/dev/null 2>&1 || true
        pct destroy "$TEMPLATE_VMID" --purge --force
    else
        log "VMID ${TEMPLATE_VMID} is free"
    fi
}

create_container() {
    log "creating container ${TEMPLATE_VMID}"

    pct create "$TEMPLATE_VMID" "local:vztmpl/${UBUNTU_TEMPLATE_FILENAME}" \
        --hostname runner-template \
        --storage "$STORAGE_POOL" \
        --rootfs "${STORAGE_POOL}:32" \
        --memory 2048 \
        --cores 2 \
        --net0 "name=eth0,bridge=${BRIDGE},ip=dhcp" \
        --features "nesting=1,keyctl=1" \
        --unprivileged 0 \
        --onboot 0 \
        --start 1
}

wait_for_network() {
    log "waiting for container network"

    local i
    for i in $(seq 1 30); do
        if pct exec "$TEMPLATE_VMID" -- getent hosts github.com >/dev/null 2>&1; then
            log "network up after ${i} attempt(s)"
            return
        fi
        sleep 2
    done

    log "container network did not come up within 60s"
    exit 1
}

install_base_packages() {
    log "installing base packages and Playwright system deps"

    in_container "$(cat <<'EOF'
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y --no-install-recommends \
    ca-certificates curl wget gnupg lsb-release \
    git jq sudo \
    build-essential pkg-config \
    libssl-dev libyaml-dev

# Playwright runtime libraries — Chromium + Firefox + WebKit on Ubuntu 24.04.
# Source: github.com/microsoft/playwright (lib/server/registry/dependencies.ts).
# Bump alongside Playwright support changes.
apt-get install -y --no-install-recommends \
    libnspr4 libnss3 libdbus-1-3 \
    libatk1.0-0t64 libatk-bridge2.0-0t64 libatspi2.0-0t64 \
    libxcomposite1 libxdamage1 libxfixes3 libxrandr2 \
    libgbm1 libxkbcommon0 \
    libpango-1.0-0 libcairo2 libasound2t64 \
    libdbus-glib-1-2 libxt6t64 \
    gstreamer1.0-libav \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    libavif16 libenchant-2-2 libepoxy0 libevdev2 libgles2 \
    libgstreamer-gl1.0-0 libgstreamer-plugins-base1.0-0 \
    libgudev-1.0-0 libharfbuzz-icu0 libhyphen0 libicu74 \
    libjpeg-turbo8 liblcms2-2 libmanette-0.2-0 \
    libopenjp2-7 libopus0 libpng16-16t64 libsecret-1-0 \
    libsoup-3.0-0 \
    libwayland-client0 libwayland-egl1 libwayland-server0 \
    libwebp7 libwebpdemux2 libwoff1 libx11-xcb1 libxml2

apt-get clean
rm -rf /var/lib/apt/lists/*
EOF
)"
}

install_docker() {
    log "installing Docker from upstream apt repo"

    in_container "$(cat <<'EOF'
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

codename="$(. /etc/os-release && echo "$VERSION_CODENAME")"
cat > /etc/apt/sources.list.d/docker.list <<DOCKER
deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${codename} stable
DOCKER

apt-get update
apt-get install -y --no-install-recommends \
    docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin

systemctl enable docker

apt-get clean
rm -rf /var/lib/apt/lists/*
EOF
)"
}

create_runner_user() {
    log "creating runner user"

    in_container "$(cat <<'EOF'
set -euo pipefail

if ! id runner >/dev/null 2>&1; then
    useradd --create-home --shell /bin/bash runner
fi

usermod -aG docker runner

cat > /etc/sudoers.d/runner <<'SUDO'
runner ALL=(ALL) NOPASSWD:ALL
SUDO
chmod 0440 /etc/sudoers.d/runner
visudo -c -f /etc/sudoers.d/runner
EOF
)"
}

# === Entrypoint ==============================================================

main() {
    log "build-runner-template.sh starting; VMID=${TEMPLATE_VMID}"
    preflight
    self_install
    ensure_ubuntu_template
    reset_vmid
    create_container
    wait_for_network
    install_base_packages
    install_docker
    create_runner_user
}

main "$@"
